[package]
name = "uasset-data-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
base64 = "0.22"

[dev-dependencies]
test_each_file = "0.3.2"