name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Linux
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          tar -cf release-${tag}-linux.tar target/x86_64-unknown-linux-gnu/release/uasset-data-parser
      - name: Build Windows
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
          zip release-${tag}-windows.zip target/x86_64-pc-windows-msvc-release-uasset-data-parser.exe
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              release-${tag}-linux.tar \
              release-${tag}-windows.zip
